pull_request_rules:
  - name: Backport to humble
    conditions:
      - base=main
      - "label=backport-humble"
    actions:
      backport:
        branches:
          - humble

  - name: Ask to resolve conflict
    conditions:
      - conflict
      - author!=mergify[bot]
      - author!=dependabot[bot]
    actions:
        comment:
          message: This pull request is in conflict. Could you fix it
                      @{{author}}?

  - name: Ask to resolve conflict for backports
    conditions:
      - conflict
      - author=mergify[bot]
    actions:
        comment:
          message: This pull request is in conflict. Could you fix it
                      @tpoignonec?

  - name: development targets main branch
    conditions:
      - base!=main
      - author!=tpoignonec
      - author!=mergify[bot]
      - author!=dependabot[bot]
    actions:
        comment:
          message: |
            @{{author}}, all pull requests must be targeted towards the `master`
            development branch. Once merged into `master`, it is possible to
            backport to `{{base}}`, but it must be in `master` to have these
            changes reflected into new distributions.
