name: CI (rolling)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - name: Prepare
        run: |
          mkdir -p ${{github.workspace}}/src
      - name: Display dir tree
        run: |
          apt install -y tree |
          tree -L 2
      - uses: actions/checkout@v4
        with:
          path: src/acados_controllers_ros2
      - uses: ros-tooling/setup-ros@v0.7
        with:
          use-ros2-testing: true
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: rolling
          vcs-repo-file-url: src/acados_controllers_ros2/acados_controllers_ros2.repos
