name: CI (humble)
on:
  push:
    branches: [ humble ]
  pull_request:
    branches: [ humble ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/action-ros-ci@0.4
        with:
          target-ros2-distro: humble
          vcs-repo-file-url: ./forcedimension_ros2.repos
