name: CI (rolling)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/action-ros-ci@0.4.3
        with:
          target-ros2-distro: rolling
          vcs-repo-file-url: ./forcedimension_ros2.repos
